# Generated by Django 5.1 on 2024-08-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('qtd_pokemons', models.IntegerField()),
                ('descricao_pokemons', models.TextField()),
                ('personagens', models.CharField(max_length=255)),
            ],
        ),
    ]
