# Generated by Django 5.1 on 2024-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeMafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('qtd_treinadores', models.IntegerField()),
                ('descricao_treinadores', models.TextField()),
                ('personagens', models.CharField(max_length=255)),
            ],
        ),
    ]
